title: CDLI
markdown: kramdown
kramdown:
  input: GFM
url: ""
baseurl: "/blog"
color_scheme: "#1762ab"
# for atom feed
author:
  name: Sagar
  email: sagar.r16@iiits.in

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

paginate_path: "/page:num/"

paginate: 5

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

collections:
  blog:
    output: true
    permalink: /:path


exclude: ['sitemap.xml','feed.xml', 'LICENSE', 'README.md']
