title: CDLI-Blog
description: Cuneiform Digital Library Initiative Blog
markdown: CommonMarkGhPages
url: ""
baseurl: "/blog"
color_scheme: "#1762ab"
# for atom feed

# kramdown:
#   html_to_native: true
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

author:
  name: Sagar
  email: sagar.r16@iiits.in

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

paginate_path: "/page:num/"

paginate: 5

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

collections:
  blog:
    output: true
    permalink: /:path


exclude: ['sitemap.xml', 'LICENSE', 'README.md']
